name: Auto Daily CheckIn

on:
  schedule:
    - cron: '0 0 2,7,13,18,23,28 * *' # 每天凌晨自动帮你签到
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger TrendRadar CheckIn
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/check_in.yml/dispatches \
          -d '{"ref":"master"}'
